config/routes.rb
Rails.application.routes.draw do
  resources :shares
  devise_for :users
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  resources :humen
  #get 'home/index'
  root 'home#index'
  get 'home/about'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/human.rb
class Human < ApplicationRecord
end

app/models/share.rb
class Share < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  	
  end
end

app/controllers/humen_controller.rb
class HumenController < ApplicationController
  before_action :set_human, only: %i[ show edit update destroy ]

  # GET /humen or /humen.json
  def index
    @humen = Human.all
  end

  # GET /humen/1 or /humen/1.json
  def show
  end

  # GET /humen/new
  def new
    @human = Human.new
  end

  # GET /humen/1/edit
  def edit
  end

  # POST /humen or /humen.json
  def create
    @human = Human.new(human_params)

    respond_to do |format|
      if @human.save
        format.html { redirect_to human_url(@human), notice: "Human was successfully created." }
        format.json { render :show, status: :created, location: @human }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @human.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /humen/1 or /humen/1.json
  def update
    respond_to do |format|
      if @human.update(human_params)
        format.html { redirect_to human_url(@human), notice: "Human was successfully updated." }
        format.json { render :show, status: :ok, location: @human }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @human.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /humen/1 or /humen/1.json
  def destroy
    @human.destroy

    respond_to do |format|
      format.html { redirect_to humen_url, notice: "Human was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_human
      @human = Human.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def human_params
      params.require(:human).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  before_action :set_share, only: %i[ show edit update destroy ]

  # GET /shares or /shares.json
  def index
    @shares = Share.all
  end

  # GET /shares/1 or /shares/1.json
  def show
  end

  # GET /shares/new
  def new
    @share = Share.new
  end

  # GET /shares/1/edit
  def edit
  end

  # POST /shares or /shares.json
  def create
    @share = Share.new(share_params)

    respond_to do |format|
      if @share.save
        format.html { redirect_to share_url(@share), notice: "Share was successfully created." }
        format.json { render :show, status: :created, location: @share }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @share.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shares/1 or /shares/1.json
  def update
    respond_to do |format|
      if @share.update(share_params)
        format.html { redirect_to share_url(@share), notice: "Share was successfully updated." }
        format.json { render :show, status: :ok, location: @share }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @share.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shares/1 or /shares/1.json
  def destroy
    @share.destroy

    respond_to do |format|
      format.html { redirect_to shares_url, notice: "Share was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_share
      @share = Share.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def share_params
      params.require(:share).permit(:stock, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/humen_helper.rb
module HumenHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Site App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Humans', humen_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'New human', new_human_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<h1>Hello World <h1>
	This is my first webpage

app/views/humen/_form.html.erb
<%= form_with(model: human) do |form| %>
  <% if human.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(human.errors.count, "error") %> prohibited this human from being saved:</h2>

      <ul>
        <% human.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/humen/_human.html.erb
<div id="<%= dom_id human %>">
  <p>
    <strong>First name:</strong>
    <%= human.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= human.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= human.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= human.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= human.twitter %>
  </p>

</div>

app/views/humen/edit.html.erb
<h1>Editing human</h1>

<%= render "form", human: @human %>

<br>

<div>
  <%= link_to "Show this human", @human %> |
  <%= link_to "Back to humen", humen_path %>
</div>

app/views/humen/index.html.erb
<h1>Human</h1>

<div id="humen">
  <% @humen.each do |human| %>
    <%= render human %>
    <p>
      <%= link_to "Show this human", human %>
    </p>
  <% end %>
</div>
<%= link_to "New human", new_human_path %>

app/views/humen/new.html.erb
<h1>New human</h1>

<%= render "form", human: @human %>

<br>

<div>
  <%= link_to "Back to humen", humen_path %>
</div>

app/views/humen/show.html.erb
<%= render @human %>

<div>
  <%= link_to "Edit this human", edit_human_path(@human) %> |
  <%= link_to "Back to humen", humen_path %>

  <%= button_to "Destroy this human", @human, method: :delete %>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Site App</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

    <%= render 'home/header' %>
    <div class="container">
<br/>
        <%if notice %>
        <%= render 'layouts/alerts' %>
        <% end %>

     
    <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/shares/_form.html.erb
<%= form_with(model: share) do |form| %>
  <% if share.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(share.errors.count, "error") %> prohibited this share from being saved:</h2>

      <ul>
        <% share.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :stock, style: "display: block" %>
    <%= form.text_field :stock %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shares/_share.html.erb
<div id="<%= dom_id share %>">
  <p>
    <strong>Stock:</strong>
    <%= share.stock %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= share.price %>
  </p>

</div>

app/views/shares/edit.html.erb
<h1>Editing share</h1>

<%= render "form", share: @share %>

<br>

<div>
  <%= link_to "Show this share", @share %> |
  <%= link_to "Back to shares", shares_path %>
</div>

app/views/shares/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Shares</h1>

<div id="shares">
  <% @shares.each do |share| %>
    <%= render share %>
    <p>
      <%= link_to "Show this share", share %>
    </p>
  <% end %>
</div>

<%= link_to "New share", new_share_path %>

app/views/shares/new.html.erb
<h1>New share</h1>

<%= render "form", share: @share %>

<br>

<div>
  <%= link_to "Back to shares", shares_path %>
</div>

app/views/shares/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @share %>

<div>
  <%= link_to "Edit this share", edit_share_path(@share) %> |
  <%= link_to "Back to shares", shares_path %>

  <%= button_to "Destroy this share", @share, method: :delete %>
</div>